#!/bin/sh
# This file was automatically generated by Spank 0.9.5
# See http://nurd.se/~noname/spank/ for more information

if [ ! -d '/tmp/spank.___home___noname___git___spank.tempfiles' ]
then
	mkdir -p '/tmp/spank.___home___noname___git___spank.tempfiles'
fi
if [ -d /tmp/spank.___home___noname___git___spank.tempfiles ]
then
echo "[ 5 %] src/compiler.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/compiler.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___compiler.cpp.o'
echo "[ 10 %] src/compilergcc.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/compilergcc.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilergcc.cpp.o'
echo "[ 15 %] src/compilermcs.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/compilermcs.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilermcs.cpp.o'
echo "[ 21 %] src/compilervala.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/compilervala.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilervala.cpp.o'
echo "[ 26 %] src/config.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/config.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___config.cpp.o'
echo "[ 31 %] src/export.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/export.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___export.cpp.o'
echo "[ 36 %] src/exportmakefile.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/exportmakefile.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___exportmakefile.cpp.o'
echo "[ 42 %] src/exportshell.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/exportshell.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___exportshell.cpp.o'
echo "[ 47 %] src/files.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/files.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___files.cpp.o'
echo "[ 52 %] src/filesunix.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/filesunix.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___filesunix.cpp.o'
echo "[ 57 %] src/installer.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/installer.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___installer.cpp.o'
echo "[ 63 %] src/installerdeb.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/installerdeb.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___installerdeb.cpp.o'
echo "[ 68 %] src/installerunix.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/installerunix.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___installerunix.cpp.o'
echo "[ 73 %] src/log.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/log.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___log.cpp.o'
echo "[ 78 %] src/main.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/main.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___main.cpp.o'
echo "[ 84 %] src/project.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/project.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___project.cpp.o'
echo "[ 89 %] src/spank.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/spank.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___spank.cpp.o'
echo "[ 94 %] src/system.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/system.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___system.cpp.o'
echo "[ 100 %] src/tools.cpp"
g++ -D'SPANK_VERSION="0.9.5"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++  -c src/tools.cpp -o '/tmp/spank.___home___noname___git___spank.tempfiles/src___tools.cpp.o'

echo "Linking..."
g++ -o 'spank' '/tmp/spank.___home___noname___git___spank.tempfiles/src___compiler.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilergcc.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilermcs.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___compilervala.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___config.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___export.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___exportmakefile.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___exportshell.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___files.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___filesunix.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___installer.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___installerdeb.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___installerunix.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___log.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___main.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___project.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___spank.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___system.cpp.o' '/tmp/spank.___home___noname___git___spank.tempfiles/src___tools.cpp.o'  -lpthread  

else
	echo "Couldn't create temp directory"
fi
