#!/bin/sh
# This file was automatically generated by Spank 0.9.5
# See http://nurd.se/~noname/spank for more information

if [ ! -d /tmp/spank.tempfiles ]
then
	mkdir -p /tmp/spank.tempfiles
fi
if [ -d /tmp/spank.tempfiles ]
then
echo "[ 5 %] src/exporters/exportmakefile.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___exporters___exportmakefile.cpp.o src/exporters/exportmakefile.cpp
echo "[ 10 %] src/exporters/exportshell.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___exporters___exportshell.cpp.o src/exporters/exportshell.cpp
echo "[ 15 %] src/compilers/compilervala.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___compilers___compilervala.cpp.o src/compilers/compilervala.cpp
echo "[ 21 %] src/compilers/compilergcc.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___compilers___compilergcc.cpp.o src/compilers/compilergcc.cpp
echo "[ 26 %] src/compilers/compilermcs.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___compilers___compilermcs.cpp.o src/compilers/compilermcs.cpp
echo "[ 31 %] src/log.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___log.cpp.o src/log.cpp
echo "[ 36 %] src/installers/installerunix.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___installers___installerunix.cpp.o src/installers/installerunix.cpp
echo "[ 42 %] src/installers/installerdeb.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___installers___installerdeb.cpp.o src/installers/installerdeb.cpp
echo "[ 47 %] src/compiler.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___compiler.cpp.o src/compiler.cpp
echo "[ 52 %] src/filesunix.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___filesunix.cpp.o src/filesunix.cpp
echo "[ 57 %] src/tools.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___tools.cpp.o src/tools.cpp
echo "[ 63 %] src/config.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___config.cpp.o src/config.cpp
echo "[ 68 %] src/export.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___export.cpp.o src/export.cpp
echo "[ 73 %] src/project.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___project.cpp.o src/project.cpp
echo "[ 78 %] src/system.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___system.cpp.o src/system.cpp
echo "[ 84 %] src/main.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___main.cpp.o src/main.cpp
echo "[ 89 %] src/files.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___files.cpp.o src/files.cpp
echo "[ 94 %] src/installer.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___installer.cpp.o src/installer.cpp
echo "[ 100 %] src/spank.cpp"
g++ -Iinclude -Wall -pedantic -ggdb -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="Spank"' -D'SPANK_BINNAME="spank"' -D'SPANK_VERSION="0.9.5"' -D'SPANK_HOMEPAGE="http://nurd.se/~noname/spank"' -D'SPANK_AUTHOR="Fredrik Hultin"' -D'SPANK_EMAIL="noname@nurd.se"' -D'SPANK_PREFIX=""' -c -o /tmp/spank.tempfiles/src___spank.cpp.o src/spank.cpp

echo "Linking..."
g++ -o spank /tmp/spank.tempfiles/src___exporters___exportmakefile.cpp.o /tmp/spank.tempfiles/src___exporters___exportshell.cpp.o /tmp/spank.tempfiles/src___compilers___compilervala.cpp.o /tmp/spank.tempfiles/src___compilers___compilergcc.cpp.o /tmp/spank.tempfiles/src___compilers___compilermcs.cpp.o /tmp/spank.tempfiles/src___log.cpp.o /tmp/spank.tempfiles/src___installers___installerunix.cpp.o /tmp/spank.tempfiles/src___installers___installerdeb.cpp.o /tmp/spank.tempfiles/src___compiler.cpp.o /tmp/spank.tempfiles/src___filesunix.cpp.o /tmp/spank.tempfiles/src___tools.cpp.o /tmp/spank.tempfiles/src___config.cpp.o /tmp/spank.tempfiles/src___export.cpp.o /tmp/spank.tempfiles/src___project.cpp.o /tmp/spank.tempfiles/src___system.cpp.o /tmp/spank.tempfiles/src___main.cpp.o /tmp/spank.tempfiles/src___files.cpp.o /tmp/spank.tempfiles/src___installer.cpp.o /tmp/spank.tempfiles/src___spank.cpp.o 

else
	echo "Couldn't create temp directory"
fi
