#!/bin/sh
# This file was automatically generated by Spank 0.9.6
# See http://nurd.se/~noname/spank/ for more information

g++ src/compiler.cpp src/compilergcc.cpp src/compilermcs.cpp src/compilervala.cpp src/config.cpp src/export.cpp src/exportmakefile.cpp src/exportshell.cpp src/files.cpp src/filesunix.cpp src/installer.cpp src/installerdeb.cpp src/installerunix.cpp src/log.cpp src/main.cpp src/project.cpp src/spank.cpp src/system.cpp src/tools.cpp -D'SPANK_VERSION="0.9.6"' -std=c++11 -Wall -pedantic -ggdb -D'SPANK_NAME="Spank"' -x c++   -lpthread   -o 'spank'
